const defaultState = {
    prestations:[],
    acteDepenses:[],
    bailleurs:[],
    banques:[],
    codesFonctions:[],
    comptes:[],
   
    lots:[],
    typePrestations:[],
    typeFactures:[],
    typeActeDepenses:[],
    acteurDepenses:[],
    analyseDossiers:[],
    cojos:[],
    motifDecisions:[],
    conditions:[],
    fonctionOccupes:[],
    natureFonctions:[],
    signatures:[],
    typeActeEffetFinanciers:[],
    typeAnalyses:[],
    typeUa:[],
    uniteAdministratives:[],
    uniteZones:[],
    factures: [],

    ligneBudgetaires:[],
    DossierCandidats:[],
    livrables:[],
      
    zoneGeographiques:[],
    typeTextJuridiques:[],
    realiteServiceFaits:[],
    text_juridiques:[],
    autresTexteJuridiques:[],
    typeTypeProcedures:[],
    procedurePassations:[],
    appelOffres:[],
    typeMarches:[],
    modePassations:[],
    marches:[],
    offreTechniques:[],
    offreFinanciers:[],
    lettreInvitation:[],
    mandate:[],
documentProcedures:[],
    stateDemandeAno:[],
    analyseDMP:[],
    stateAnoDmpBailleur:[],
    obseravtionBailleurs:[],
    nouveauFournisseur:[],
    acteEffetFinanciers: [],
    engagements: [],
    mandats:[],
    executionMarches:[],
    typeAppelOffre: [],

    typeCandidat: [],
    pays: [],
    villes: [],
    communes:[],

    bailleurMarche: [],
    choixprocedure: [],
     membre_cojo:[],
    proce_verballe:[],
    avenants:[]



}

export default defaultState;
