const defaultState = {

budgetEclateImporter:[],
    prestations: [],
    acteDepenses: [],
    bailleurs: [],
    banques: [],
    codesFonctions: [],
    comptes: [],
    receptionMarche: [],
    lots: [],
    typePrestations: [],
    typeFactures: [],
    typeActeDepenses: [],
    acteurDepenses: [],
    analyseDossiers: [],
    cojos: [],
    motifDecisions: [],
    conditions: [],
    fonctionOccupes: [],
    natureFonctions: [],
    signatures: [],
    typeActeEffetFinanciers: [],
    typeAnalyses: [],
    typeUa: [],
    uniteAdministratives: [],
    uniteZones: [],
    factures: [],

    ligneBudgetaires: [],
    DossierCandidats: [],
    livrables: [],

    reserve_cf: [],
    arnmps: [],
    organes_decision: [],
    nature_prix: [],
    motif_passations: [],


    documentMedias: [],
    rapportDocuments: [],
    cojo_personnels: [],

    // mediaStock:[],
    // stockDocuments:[],

    zoneGeographiques: [],
    typeTextJuridiques: [],
    realiteServiceFaits: [],
    text_juridiques: [],
    autresTexteJuridiques: [],
    typeTypeProcedures: [],
    procedurePassations: [],
    appelOffres: [],
    typeMarches: [],
    modePassations: [],
    marches: [],
    offreTechniques: [],
    offreFinanciers: [],
    lettreInvitation: [],
    mandate: [],
    documentProcedures: [],
    stateDemandeAno: [],
    analyseDMP: [],
    stateAnoDmpBailleur: [],
    obseravtionBailleurs: [],
    nouveauFournisseur: [],
    acteEffetFinanciers: [],
    engagements: [],
    mandats: [],
    executionMarches: [],
    typeAppelOffre: [],

    typeCandidat: [],
    pays: [],
    villes: [],
    communes: [],
    bailleurMarche: [],
    choixprocedure: [],
    membre_cojo: [],
    proce_verballe: [],
    avenants: [],
    modepaiements: [],
    stateCotations: [],
    gettersOuvertures: [],
    gettersEtatProcedure: [],
    gettersPsc: [],
    stateTransmissions: [],
    rapportOuverture: [],
    gettersTransmissions: [],
    plan_passation_marche: [],
    voirBudgetImporter: [],
    role_membrecojo: [],
    selectionner_candidats: [],


    echeances: [],

    image_marche: [],
    typeOrdrePaiement: [],
    loading_marche: true,
    marcheFiltreCarteInfrastructure: "",
    informationFiltreCarteInfrastructure: "",



    tableauBordFilter: "",
    infoFiltreTableauBord: "",
    membre_comite_evaluations: [],
    structure_daos: [],
    TacheMarche: [],
    entreprise_soustraitant: [],
    programmationMarchePlurieAnnuel: [],
    DemandeEngagement: [],
    nomPieceJustificative: [],
    Liquidation: [],
    MandatOp: [],
    facturePiece: [],
    AutreDepense: [],
    gestionOrdrePaiement: [],
    gestionOrdrePaiementAnnulation: [],
    ServiceRealiteFaitOp: [],
    historiqueDecisionCfOP: [],
    ProblemeMarche: [],
    ProcedureDroitCommuns: [],
    ProcedureDerogatoires: [],

}

export default defaultState;
