const defaultState = {
    prestations:[],
    acteDepenses:[],
    bailleurs:[],
    banques:[],
    codesFonctions:[],
    comptes:[],
   
    lots:[],
    typePrestations:[],
    typeFactures:[],
    typeActeDepenses:[],
    acteurDepenses:[],
    analyseDossiers:[],
    cojos:[],
    motifDecisions:[],
    conditions:[],
    fonctionOccupes:[],
    natureFonctions:[],
    signatures:[],
    typeActeEffetFinanciers:[],
    typeAnalyses:[],
    typeUa:[],
    uniteAdministratives:[],
    uniteZones:[],
    factures: [],

    ligneBudgetaires:[],
    DossierCandidats:[],
    livrables:[],

    // documents:[],
    // rapportJugements:[],
    // rapportOuverture1:[],
    // rapportOuverture2:[],

    documentMedias:[],
    rapportDocuments:[],
    cojo_personnels:[],

    // mediaStock:[],
    // stockDocuments:[],

    zoneGeographiques:[],
    typeTextJuridiques:[],
    realiteServiceFaits:[],
    text_juridiques:[],
    autresTexteJuridiques:[],
    typeTypeProcedures:[],
    procedurePassations:[],
    appelOffres:[],
    typeMarches:[],
    modePassations:[],
    marches:[],
    offreTechniques:[],
    offreFinanciers:[],
    lettreInvitation:[],
    mandate:[],
    documentProcedures:[],
    stateDemandeAno:[],
    analyseDMP:[],
    stateAnoDmpBailleur:[],
    obseravtionBailleurs:[],
    nouveauFournisseur:[],
    acteEffetFinanciers: [],
    engagements: [],
    mandats:[],
    executionMarches:[],
    typeAppelOffre: [],

    typeCandidat: [],
    pays: [],
    villes: [],
    communes:[],
    bailleurMarche: [],
    choixprocedure: [],
     membre_cojo:[],
    proce_verballe:[],
    avenants:[],
    modepaiements:[],
    stateCotations:[],
    gettersOuvertures:[],
    gettersEtatProcedure:[],
    gettersPsc:[],
    stateTransmissions:[],
    rapportOuverture:[],
    gettersTransmissions:[],
    plan_passation_marche:[],

    role_membrecojo: [],
    selectionner_candidats:[],


    echeances:[]
  

}

export default defaultState;
